services:
  edookit:
    image: stanfuhx/edookit:1
    env_file:
      - .env
    environment:
      - CRON_INTERVAL=1800
    volumes:
      - ./cookies.json:/data/cookies.json
    restart: unless-stopped
